const REF_TO_LOCATION = {
  AVR: ['Aveiro', 'Aveiro'],
  SJM: ['São João da Madeira', 'Aveiro'],
  SMP: ['Santa Marta de Penaguião', 'Vila Real'],
  OAZ: ['Oliveira de Azeméis', 'Aveiro'],
  OVR: ['Ovar', 'Aveiro'],
  ILH: ['Ílhavo', 'Aveiro'],
  AGD: ['Águeda', 'Aveiro'],
  ETR: ['Estarreja', 'Aveiro'],
  AND: ['Anadia', 'Aveiro'],
  ALB: ['Albergaria-a-Velha', 'Aveiro'],
  CPV: ['Castelo de Paiva', 'Aveiro'],
  ESP: ['Espinho', 'Aveiro'],
  MRS: ['Murtosa', 'Aveiro'],
  OBR: ['Oliveira do Bairro', 'Aveiro'],
  SVV: ['Sever do Vouga', 'Aveiro'],
  VGS: ['Vagos', 'Aveiro'],
  VLC: ['Vale de Cambra', 'Aveiro'],
  ARC: ['Arouca', 'Aveiro'],
  BJA: ['Beja', 'Beja'],
  ODM: ['Odemira', 'Beja'],
  SRP: ['Serpa', 'Beja'],
  MOU: ['Moura', 'Beja'],
  AJT: ['Aljustrel', 'Beja'],
  AVT: ['Alvito', 'Beja'],
  BRC: ['Barrancos', 'Beja'],
  CVR: ['Castro Verde', 'Beja'],
  CBA: ['Cuba', 'Beja'],
  FAL: ['Ferreira do Alentejo', 'Beja'],
  MOR: ['Mértola', 'Beja'],
  ORQ: ['Ourique', 'Beja'],
  BRG: ['Braga', 'Braga'],
  GMR: ['Guimarães', 'Braga'],
  VNF: ['Vila Nova de Famalicão', 'Braga'],
  BCL: ['Barcelos', 'Braga'],
  FAF: ['Fafe', 'Braga'],
  EPS: ['Esposende', 'Braga'],
  VIZ: ['Vizela', 'Braga'],
  AMR: ['Amares', 'Braga'],
  CBT: ['Cabeceiras de Basto', 'Braga'],
  CLB: ['Câmara de Lobos', 'Ilha da Madeira'],
  PVL: ['Póvoa de Lanhoso', 'Braga'],
  TBR: ['Terras de Bouro', 'Braga'],
  VVR: ['Vila Velha de Ródão', 'Castelo Branco'],
  VVD: ['Vila Verde', 'Braga'],
  BGC: ['Bragança', 'Bragança'],
  MLD: ['Mirandela', 'Bragança'],
  MCV: ['Macedo de Cavaleiros', 'Bragança'],
  AFE: ['Alfândega da Fé', 'Bragança'],
  CRZ: ['Carrazeda de Ansiães', 'Bragança'],
  FEC: ['Freixo de Espada à Cinta', 'Bragança'],
  MDR: ['Miranda do Douro', 'Bragança'],
  MGD: ['Mogadouro', 'Bragança'],
  TMC: ['Torre de Moncorvo', 'Bragança'],
  VFL: ['Vila Flor', 'Bragança'],
  VMS: ['Vimioso', 'Bragança'],
  VNH: ['Vinhais', 'Bragança'],
  CTB: ['Castelo Branco', 'Castelo Branco'],
  CVL: ['Covilhã', 'Castelo Branco'],
  FND: ['Fundão', 'Castelo Branco'],
  SRT: ['Sertã', 'Castelo Branco'],
  BMT: ['Belmonte', 'Castelo Branco'],
  IDN: ['Idanha-a-Nova', 'Castelo Branco'],
  OLR: ['Oleiros', 'Castelo Branco'],
  PNC: ['Penamacor', 'Castelo Branco'],
  PNV: ['Proença-a-Nova', 'Castelo Branco'],
  VLR: ['Vila de Rei', 'Castelo Branco'],
  CBR: ['Coimbra', 'Coimbra'],
  FIG: ['Figueira da Foz', 'Coimbra'],
  CNT: ['Cantanhede', 'Coimbra'],
  OHP: ['Oliveira do Hospital', 'Coimbra'],
  CDN: ['Condeixa-a-Nova', 'Coimbra'],
  AGN: ['Arganil', 'Coimbra'],
  GOI: ['Góis', 'Coimbra'],
  LSA: ['Lousã', 'Coimbra'],
  MIR: ['Mira', 'Coimbra'],
  MCN: ['Marco de Canaveses', 'Porto'],
  MMV: ['Montemor-o-Velho', 'Coimbra'],
  PPS: ['Pampilhosa da Serra', 'Coimbra'],
  PNL: ['Penalva do Castelo', 'Viseu'],
  SRE: ['Soure', 'Coimbra'],
  TBU: ['Tábua', 'Coimbra'],
  VNP: ['Vila Nova de Paiva', 'Viseu'],
  EVR: ['Évora', 'Évora'],
  ETZ: ['Estremoz', 'Évora'],
  MMN: ['Montemor-o-Novo', 'Évora'],
  VND: ['Vendas Novas', 'Évora'],
  ADL: ['Alandroal', 'Évora'],
  ARL: ['Arraiolos', 'Évora'],
  BRB: ['Borba', 'Évora'],
  MRA: ['Mora', 'Évora'],
  MTR: ['Mourão', 'Évora'],
  PTL: ['Ponte de Lima', 'Viana do Castelo'],
  RDD: ['Redondo', 'Évora'],
  RMZ: ['Reguengos de Monsaraz', 'Évora'],
  VNT: ['Viana do Alentejo', 'Évora'],
  VVC: ['Vila Viçosa', 'Évora'],
  FAR: ['Faro', 'Faro'],
  PTM: ['Portimão', 'Faro'],
  LLE: ['Loulé', 'Faro'],
  ABF: ['Albufeira', 'Faro'],
  SLV: ['Silves', 'Faro'],
  LAG: ['Lagos', 'Faro'],
  TVR: ['Tavira', 'Faro'],
  OLH: ['Olhão', 'Faro'],
  VRS: ['Vila Real de Santo António', 'Faro'],
  AJZ: ['Aljezur', 'Faro'],
  ACT: ['Alcoutim', 'Faro'],
  MCQ: ['Monchique', 'Faro'],
  SBA: ['São Brás de Alportel', 'Faro'],
  VBP: ['Vila do Bispo', 'Faro'],
  GRD: ['Grândola', 'Setúbal'],
  SEI: ['Seia', 'Guarda'],
  GVA: ['Gouveia', 'Guarda'],
  AGB: ['Aguiar da Beira', 'Guarda'],
  ALD: ['Almeida', 'Guarda'],
  FCR: ['Figueira de Castelo Rodrigo', 'Guarda'],
  FAG: ['Fornos de Algodres', 'Guarda'],
  MTG: ['Manteigas', 'Guarda'],
  MED: ['Mêda', 'Guarda'],
  PNH: ['Pinhel', 'Guarda'],
  SBG: ['Sabugal', 'Guarda'],
  TRC: ['Tarouca', 'Viseu'],
  VNC: ['Vila Nova de Cerveira', 'Viana do Castelo'],
  LRA: ['Leiria', 'Leiria'],
  ACB: ['Alcobaça', 'Leiria'],
  CLD: ['Caldas da Rainha', 'Leiria'],
  PBL: ['Pombal', 'Leiria'],
  MGR: ['Marinha Grande', 'Leiria'],
  NZR: ['Nazaré', 'Leiria'],
  BTL: ['Batalha', 'Leiria'],
  BBR: ['Bombarral', 'Leiria'],
  CPR: ['Castanheira de Pera', 'Leiria'],
  OBD: ['Óbidos', 'Leiria'],
  PGR: ['Pedrógão Grande', 'Leiria'],
  PMS: ['Porto de Mós', 'Leiria'],
  LSB: ['Lisboa', 'Lisboa'],
  SNT: ['Sintra', 'Lisboa'],
  CSC: ['Cascais', 'Lisboa'],
  LRS: ['Loures', 'Lisboa'],
  AMD: ['Amadora', 'Lisboa'],
  OER: ['Oeiras', 'Lisboa'],
  ODV: ['Odivelas', 'Lisboa'],
  VFX: ['Vila Franca de Xira', 'Lisboa'],
  MFR: ['Mafra', 'Lisboa'],
  TVD: ['Torres Vedras', 'Lisboa'],
  ALQ: ['Alenquer', 'Lisboa'],
  LNH: ['Lourinhã', 'Lisboa'],
  CDV: ['Cadaval', 'Lisboa'],
  SMA: ['Sobral de Monte Agraço', 'Lisboa'],
  ARV: ['Arruda dos Vinhos', 'Lisboa'],
  PTG: ['Portalegre', 'Portalegre'],
  ELV: ['Elvas', 'Portalegre'],
  PSR: ['Ponte de Sor', 'Portalegre'],
  ALT: ['Alter do Chão', 'Portalegre'],
  ARR: ['Arronches', 'Portalegre'],
  AVS: ['Avis', 'Portalegre'],
  CMR: ['Campo Maior', 'Portalegre'],
  CVD: ['Castelo de Vide', 'Portalegre'],
  CRT: ['Crato', 'Portalegre'],
  FTR: ['Fronteira', 'Portalegre'],
  GAV: ['Gavião', 'Portalegre'],
  MRV: ['Marvão', 'Portalegre'],
  MFT: ['Monforte', 'Portalegre'],
  NIS: ['Nisa', 'Portalegre'],
  SSL: ['Sousel', 'Portalegre'],
  SCR: ['Sousel', 'Portalegre'],
  PRT: ['Porto', 'Porto'],
  VNG: ['Vila Nova de Gaia', 'Porto'],
  MTS: ['Matosinhos', 'Porto'],
  MAI: ['Maia', 'Porto'],
  GDM: ['Gondomar', 'Porto'],
  VLG: ['Valongo', 'Porto'],
  PVZ: ['Póvoa de Varzim', 'Porto'],
  VCD: ['Vila do Conde', 'Porto'],
  STS: ['Santo Tirso', 'Porto'],
  PNF: ['Penafiel', 'Porto'],
  AMT: ['Amarante', 'Porto'],
  FLG: ['Felgueiras', 'Porto'],
  LSD: ['Lousada', 'Porto'],
  PFR: ['Paços de Ferreira', 'Porto'],
  PRD: ['Paredes', 'Porto'],
  BAO: ['Baião', 'Porto'],
  TRF: ['Trofa', 'Porto'],
  STR: ['Santarém', 'Santarém'],
  ORM: ['Ourém', 'Santarém'],
  TMR: ['Tomar', 'Santarém'],
  ABT: ['Abrantes', 'Santarém'],
  TNV: ['Torres Novas', 'Santarém'],
  ENT: ['Entroncamento', 'Santarém'],
  CTX: ['Cartaxo', 'Santarém'],
  ALR: ['Almeirim', 'Santarém'],
  APC: ['Alpiarça', 'Santarém'],
  BNV: ['Benavente', 'Santarém'],
  CHM: ['Chamusca', 'Santarém'],
  CNS: ['Constância', 'Santarém'],
  CCH: ['Coruche', 'Santarém'],
  FZZ: ['Ferreira do Zêzere', 'Santarém'],
  GLG: ['Golegã', 'Santarém'],
  MAC: ['Mação', 'Santarém'],
  RMR: ['Rio Maior', 'Santarém'],
  SMG: ['Salvaterra de Magos', 'Santarém'],
  SRD: ['Sardoal', 'Santarém'],
  VNB: ['Vila Nova da Barquinha', 'Santarém'],
  STB: ['Setúbal', 'Setúbal'],
  ALM: ['Almada', 'Setúbal'],
  SXL: ['Seixal', 'Setúbal'],
  BRR: ['Barreiro', 'Setúbal'],
  PLM: ['Palmela', 'Setúbal'],
  MTA: ['Moita', 'Setúbal'],
  SSB: ['Sesimbra', 'Setúbal'],
  MTJ: ['Montijo', 'Setúbal'],
  ACH: ['Alcochete', 'Setúbal'],
  STC: ['Santiago do Cacém', 'Setúbal'],
  SNS: ['Sines', 'Setúbal'],
  ASL: ['Alcácer do Sal', 'Setúbal'],
  VCT: ['Viana do Castelo', 'Viana do Castelo'],
  AVV: ['Arcos de Valdevez', 'Viana do Castelo'],
  CMN: ['Caminha', 'Viana do Castelo'],
  MLG: ['Melgaço', 'Viana do Castelo'],
  MNC: ['Monção', 'Viana do Castelo'],
  PCR: ['Paredes de Coura', 'Viana do Castelo'],
  PTB: ['Ponte da Barca', 'Viana do Castelo'],
  VLN: ['Valença', 'Viana do Castelo'],
  VRL: ['Vila Real', 'Vila Real'],
  CHV: ['Chaves', 'Vila Real'],
  VLP: ['Valpaços', 'Vila Real'],
  ALJ: ['Alijó', 'Vila Real'],
  BTC: ['Boticas', 'Vila Real'],
  MSF: ['Mesão Frio', 'Vila Real'],
  MDB: ['Moimenta da Beira', 'Viseu'],
  MGL: ['Mangualde', 'Viseu'],
  MUR: ['Murça', 'Vila Real'],
  RPN: ['Ribeira de Pena', 'Vila Real'],
  SBR: ['Sabrosa', 'Vila Real'],
  VPA: ['Vila Pouca de Aguiar', 'Vila Real'],
  VIS: ['Viseu', 'Viseu'],
  LMG: ['Lamego', 'Viseu'],
  SPS: ['São Pedro do Sul', 'Viseu'],
  TND: ['Tondela', 'Viseu'],
  AMM: ['Armamar', 'Viseu'],
  CRS: ['Carregal do Sal', 'Viseu'],
  CDR: ['Castro Daire', 'Viseu'],
  CNF: ['Cinfães', 'Viseu'],
  MRT: ['Mortágua', 'Viseu'],
  NLS: ['Nelas', 'Viseu'],
  OFR: ['Oliveira de Frades', 'Viseu'],
  PND: ['Penedono', 'Viseu'],
  RSD: ['Resende', 'Viseu'],
  SCD: ['Santa Comba Dão', 'Viseu'],
  SJP: ['São João da Pesqueira', 'Viseu'],
  SAT: ['Sátão', 'Viseu'],
  SRN: ['Sernancelhe', 'Viseu'],
  TBC: ['Tabuaço', 'Viseu'],
  VZL: ['Vouzela', 'Viseu'],
  FNC: ['Funchal', 'Ilha da Madeira'],
  SCZ: ['Santa Cruz', 'Ilha da Madeira'],
  MCH: ['Machico', 'Ilha da Madeira'],
  RBR: ['Ribeira Brava', 'Ilha da Madeira'],
  CLT: ['Calheta', 'Ilhas Açores (Outras)'],
  PST: ['Porto Santo', 'Ilha da Madeira'],
  PMZ: ['Porto Moniz', 'Ilha da Madeira'],
  SVC: ['São Vicente', 'Ilha da Madeira'],
  STN: ['Santana', 'Ilha da Madeira'],
  MAD: ['Madalena', 'Ilhas Açores (Outras)'],
  PDL: ['Ponta Delgada', 'Ilha de São Miguel'],
  RGR: ['Ribeira Grande', 'Ilha de São Miguel'],
  LGA: ['Lagoa', 'Ilha de São Miguel'],
  VFC: ['Vila Franca do Campo', 'Ilha de São Miguel'],
  PVC: ['Povoação', 'Ilha de São Miguel'],
  NRD: ['Nordeste', 'Ilha de São Miguel'],
  AGH: ['Angra do Heroísmo', 'Ilhas Açores (Outras)'],
  PVT: ['Praia da Vitória', 'Ilhas Açores (Outras)'],
  HRT: ['Horta', 'Ilhas Açores (Outras)'],
  SRQ: ['São Roque do Pico', 'Ilhas Açores (Outras)'],
  LGP: ['Lajes do Pico', 'Ilhas Açores (Outras)'],
  VLS: ['Velas', 'Ilhas Açores (Outras)'],
  SCG: ['Santa Cruz da Graciosa', 'Ilhas Açores (Outras)'],
  VPT: ['Vila do Porto', 'Ilhas Açores (Outras)'],
  SCF: ['Santa Cruz das Flores', 'Ilhas Açores (Outras)'],
  LGF: ['Lajes das Flores', 'Ilhas Açores (Outras)'],
  VCR: ['Vila do Corvo', 'Ilhas Açores (Outras)'],
  EXPO: ['Lisboa', 'Lisboa'],
  FEUP: ['Porto', 'Porto'],
  ISEP: ['Porto', 'Porto'],
  IPCA: ['Barcelos', 'Braga'],
  IPL: ['Leiria', 'Leiria'],
  IPS: ['Setúbal', 'Setúbal'],
  INIAV: ['Oeiras', 'Lisboa'],
  RAM: ['Funchal', 'Ilha da Madeira'],
  FUN: ['Funchal', 'Ilha da Madeira'],
  PNI: ['Peniche', 'Leiria'],
  PRL: ['Portel', 'Évora'],
  DPC: ['Portugal', 'Outros'],
  Aguas: ['Lisboa', 'Lisboa'],
};

const DISTRICT_MAP = {
  'Águeda': 'Aveiro', 'Albergaria-a-Velha': 'Aveiro', 'Anadia': 'Aveiro',
  'Arouca': 'Aveiro', 'Aveiro': 'Aveiro', 'Castelo de Paiva': 'Aveiro',
  'Espinho': 'Aveiro', 'Estarreja': 'Aveiro', 'Ílhavo': 'Aveiro',
  'Mealhada': 'Aveiro', 'Murtosa': 'Aveiro', 'Oliveira de Azeméis': 'Aveiro',
  'Oliveira do Bairro': 'Aveiro', 'Ovar': 'Aveiro', 'Santa Maria da Feira': 'Aveiro',
  'São João da Madeira': 'Aveiro', 'Sever do Vouga': 'Aveiro',
  'Vagos': 'Aveiro', 'Vale de Cambra': 'Aveiro',
  'Aljustrel': 'Beja', 'Almodôvar': 'Beja', 'Alvito': 'Beja',
  'Barrancos': 'Beja', 'Beja': 'Beja', 'Castro Verde': 'Beja',
  'Cuba': 'Beja', 'Ferreira do Alentejo': 'Beja', 'Mértola': 'Beja',
  'Moura': 'Beja', 'Odemira': 'Beja', 'Ourique': 'Beja',
  'Serpa': 'Beja', 'Vidigueira': 'Beja',
  'Amares': 'Braga', 'Barcelos': 'Braga', 'Braga': 'Braga',
  'Cabeceiras de Basto': 'Braga', 'Celorico de Basto': 'Braga',
  'Esposende': 'Braga', 'Fafe': 'Braga', 'Guimarães': 'Braga',
  'Póvoa de Lanhoso': 'Braga', 'Terras de Bouro': 'Braga',
  'Vieira do Minho': 'Braga', 'Vila Nova de Famalicão': 'Braga',
  'Vila Verde': 'Braga', 'Vizela': 'Braga',
  'Alfândega da Fé': 'Bragança', 'Bragança': 'Bragança',
  'Carrazeda de Ansiães': 'Bragança', 'Freixo de Espada à Cinta': 'Bragança',
  'Macedo de Cavaleiros': 'Bragança', 'Miranda do Douro': 'Bragança',
  'Mirandela': 'Bragança', 'Mogadouro': 'Bragança',
  'Torre de Moncorvo': 'Bragança', 'Vila Flor': 'Bragança',
  'Vimioso': 'Bragança', 'Vinhais': 'Bragança',
  'Belmonte': 'Castelo Branco', 'Castelo Branco': 'Castelo Branco',
  'Covilhã': 'Castelo Branco', 'Fundão': 'Castelo Branco',
  'Idanha-a-Nova': 'Castelo Branco', 'Oleiros': 'Castelo Branco',
  'Penamacor': 'Castelo Branco', 'Proença-a-Nova': 'Castelo Branco',
  'Sertã': 'Castelo Branco', 'Vila de Rei': 'Castelo Branco',
  'Vila Velha de Ródão': 'Castelo Branco',
  'Arganil': 'Coimbra', 'Cantanhede': 'Coimbra', 'Coimbra': 'Coimbra',
  'Condeixa-a-Nova': 'Coimbra', 'Figueira da Foz': 'Coimbra',
  'Góis': 'Coimbra', 'Lousã': 'Coimbra', 'Mira': 'Coimbra',
  'Miranda do Corvo': 'Coimbra', 'Montemor-o-Velho': 'Coimbra',
  'Oliveira do Hospital': 'Coimbra', 'Pampilhosa da Serra': 'Coimbra',
  'Penacova': 'Coimbra', 'Penela': 'Coimbra', 'Soure': 'Coimbra',
  'Tábua': 'Coimbra', 'Vila Nova de Poiares': 'Coimbra',
  'Alandroal': 'Évora', 'Arraiolos': 'Évora', 'Borba': 'Évora',
  'Estremoz': 'Évora', 'Évora': 'Évora', 'Montemor-o-Novo': 'Évora',
  'Mora': 'Évora', 'Mourão': 'Évora', 'Portel': 'Évora',
  'Redondo': 'Évora', 'Reguengos de Monsaraz': 'Évora',
  'Vendas Novas': 'Évora', 'Viana do Alentejo': 'Évora',
  'Vila Viçosa': 'Évora',
  'Albufeira': 'Faro', 'Alcoutim': 'Faro', 'Aljezur': 'Faro',
  'Castro Marim': 'Faro', 'Faro': 'Faro', 'Lagoa': 'Faro',
  'Lagos': 'Faro', 'Loulé': 'Faro', 'Monchique': 'Faro',
  'Olhão': 'Faro', 'Portimão': 'Faro', 'São Brás de Alportel': 'Faro',
  'Silves': 'Faro', 'Tavira': 'Faro', 'Vila do Bispo': 'Faro',
  'Vila Real de Santo António': 'Faro',
  'Aguiar da Beira': 'Guarda', 'Almeida': 'Guarda',
  'Celorico da Beira': 'Guarda', 'Figueira de Castelo Rodrigo': 'Guarda',
  'Fornos de Algodres': 'Guarda', 'Gouveia': 'Guarda', 'Guarda': 'Guarda',
  'Manteigas': 'Guarda', 'Mêda': 'Guarda', 'Pinhel': 'Guarda',
  'Sabugal': 'Guarda', 'Seia': 'Guarda', 'Trancoso': 'Guarda',
  'Vila Nova de Foz Côa': 'Guarda',
  'Alcobaça': 'Leiria', 'Alvaiázere': 'Leiria', 'Ansião': 'Leiria',
  'Batalha': 'Leiria', 'Bombarral': 'Leiria', 'Caldas da Rainha': 'Leiria',
  'Castanheira de Pera': 'Leiria', 'Figueiró dos Vinhos': 'Leiria',
  'Leiria': 'Leiria', 'Marinha Grande': 'Leiria', 'Nazaré': 'Leiria',
  'Óbidos': 'Leiria', 'Pedrógão Grande': 'Leiria', 'Peniche': 'Leiria',
  'Pombal': 'Leiria', 'Porto de Mós': 'Leiria',
  'Alenquer': 'Lisboa', 'Amadora': 'Lisboa', 'Arruda dos Vinhos': 'Lisboa',
  'Azambuja': 'Lisboa', 'Cadaval': 'Lisboa', 'Cascais': 'Lisboa',
  'Lisboa': 'Lisboa', 'Loures': 'Lisboa', 'Lourinhã': 'Lisboa',
  'Mafra': 'Lisboa', 'Odivelas': 'Lisboa', 'Oeiras': 'Lisboa',
  'Sintra': 'Lisboa', 'Sobral de Monte Agraço': 'Lisboa',
  'Torres Vedras': 'Lisboa', 'Vila Franca de Xira': 'Lisboa',
  'Alter do Chão': 'Portalegre', 'Arronches': 'Portalegre', 'Avis': 'Portalegre',
  'Campo Maior': 'Portalegre', 'Castelo de Vide': 'Portalegre',
  'Crato': 'Portalegre', 'Elvas': 'Portalegre', 'Fronteira': 'Portalegre',
  'Gavião': 'Portalegre', 'Marvão': 'Portalegre', 'Monforte': 'Portalegre',
  'Nisa': 'Portalegre', 'Ponte de Sor': 'Portalegre', 'Portalegre': 'Portalegre',
  'Sousel': 'Portalegre',
  'Amarante': 'Porto', 'Baião': 'Porto', 'Felgueiras': 'Porto',
  'Gondomar': 'Porto', 'Lousada': 'Porto', 'Maia': 'Porto',
  'Marco de Canaveses': 'Porto', 'Matosinhos': 'Porto',
  'Paços de Ferreira': 'Porto', 'Paredes': 'Porto', 'Penafiel': 'Porto',
  'Porto': 'Porto', 'Póvoa de Varzim': 'Porto', 'Santo Tirso': 'Porto',
  'Trofa': 'Porto', 'Valongo': 'Porto', 'Vila do Conde': 'Porto',
  'Vila Nova de Gaia': 'Porto',
  'Abrantes': 'Santarém', 'Alcanena': 'Santarém', 'Almeirim': 'Santarém',
  'Alpiarça': 'Santarém', 'Benavente': 'Santarém', 'Cartaxo': 'Santarém',
  'Chamusca': 'Santarém', 'Constância': 'Santarém', 'Coruche': 'Santarém',
  'Entroncamento': 'Santarém', 'Ferreira do Zêzere': 'Santarém',
  'Golegã': 'Santarém', 'Mação': 'Santarém', 'Ourém': 'Santarém',
  'Rio Maior': 'Santarém', 'Salvaterra de Magos': 'Santarém',
  'Santarém': 'Santarém', 'Sardoal': 'Santarém', 'Tomar': 'Santarém',
  'Torres Novas': 'Santarém', 'Vila Nova da Barquinha': 'Santarém',
  'Alcácer do Sal': 'Setúbal', 'Alcochete': 'Setúbal', 'Almada': 'Setúbal',
  'Barreiro': 'Setúbal', 'Grândola': 'Setúbal', 'Moita': 'Setúbal',
  'Montijo': 'Setúbal', 'Palmela': 'Setúbal', 'Santiago do Cacém': 'Setúbal',
  'Seixal': 'Setúbal', 'Sesimbra': 'Setúbal', 'Setúbal': 'Setúbal',
  'Sines': 'Setúbal',
  'Arcos de Valdevez': 'Viana do Castelo', 'Caminha': 'Viana do Castelo',
  'Melgaço': 'Viana do Castelo', 'Monção': 'Viana do Castelo',
  'Paredes de Coura': 'Viana do Castelo', 'Ponte da Barca': 'Viana do Castelo',
  'Ponte de Lima': 'Viana do Castelo', 'Valença': 'Viana do Castelo',
  'Viana do Castelo': 'Viana do Castelo', 'Vila Nova de Cerveira': 'Viana do Castelo',
  'Alijó': 'Vila Real', 'Boticas': 'Vila Real', 'Chaves': 'Vila Real',
  'Mesão Frio': 'Vila Real', 'Mondim de Basto': 'Vila Real',
  'Montalegre': 'Vila Real', 'Murça': 'Vila Real',
  'Peso da Régua': 'Vila Real', 'Ribeira de Pena': 'Vila Real',
  'Sabrosa': 'Vila Real', 'Santa Marta de Penaguião': 'Vila Real',
  'Valpaços': 'Vila Real', 'Vila Pouca de Aguiar': 'Vila Real',
  'Vila Real': 'Vila Real',
  'Armamar': 'Viseu', 'Carregal do Sal': 'Viseu', 'Castro Daire': 'Viseu',
  'Cinfães': 'Viseu', 'Lamego': 'Viseu', 'Mangualde': 'Viseu',
  'Moimenta da Beira': 'Viseu', 'Mortágua': 'Viseu', 'Nelas': 'Viseu',
  'Oliveira de Frades': 'Viseu', 'Penalva do Castelo': 'Viseu',
  'Penedono': 'Viseu', 'Resende': 'Viseu', 'Santa Comba Dão': 'Viseu',
  'São João da Pesqueira': 'Viseu', 'São Pedro do Sul': 'Viseu',
  'Sátão': 'Viseu', 'Sernancelhe': 'Viseu', 'Tabuaço': 'Viseu',
  'Tarouca': 'Viseu', 'Tondela': 'Viseu', 'Vila Nova de Paiva': 'Viseu',
  'Viseu': 'Viseu', 'Vouzela': 'Viseu',
  'Calheta': 'Ilha da Madeira', 'Câmara de Lobos': 'Ilha da Madeira',
  'Funchal': 'Ilha da Madeira', 'Machico': 'Ilha da Madeira',
  'Ponta do Sol': 'Ilha da Madeira', 'Porto Moniz': 'Ilha da Madeira',
  'Porto Santo': 'Ilha da Madeira', 'Ribeira Brava': 'Ilha da Madeira',
  'Santa Cruz': 'Ilha da Madeira', 'Santana': 'Ilha da Madeira',
  'São Vicente': 'Ilha da Madeira',
  'Angra do Heroísmo': 'Ilhas Açores (Outras)',
  'Calheta': 'Ilhas Açores (Outras)',
  'Corvo': 'Ilhas Açores (Outras)',
  'Horta': 'Ilhas Açores (Outras)',
  'Lagoa': 'Ilha de São Miguel',
  'Lajes das Flores': 'Ilhas Açores (Outras)',
  'Lajes do Pico': 'Ilhas Açores (Outras)',
  'Madalena': 'Ilhas Açores (Outras)',
  'Nordeste': 'Ilha de São Miguel',
  'Ponta Delgada': 'Ilha de São Miguel',
  'Povoação': 'Ilha de São Miguel',
  'Praia da Vitória': 'Ilhas Açores (Outras)',
  'Ribeira Grande': 'Ilha de São Miguel',
  'Santa Cruz da Graciosa': 'Ilhas Açores (Outras)',
  'Santa Cruz das Flores': 'Ilhas Açores (Outras)',
  'São Roque do Pico': 'Ilhas Açores (Outras)',
  'Velas': 'Ilhas Açores (Outras)',
  'Vila do Corvo': 'Ilhas Açores (Outras)',
  'Vila do Porto': 'Ilhas Açores (Outras)',
  'Vila Franca do Campo': 'Ilha de São Miguel',
};

const PARISH_TO_CONCELHO = {
  'Alcabideche': ['Cascais', 'Lisboa'],
  'Alcains': ['Castelo Branco', 'Castelo Branco'],
  'Alcoitão': ['Cascais', 'Lisboa'],
  'Aldeia das Açoteias': ['Albufeira', 'Faro'],
  'Alfena': ['Valongo', 'Porto'],
  'Alhos Vedros': ['Moita', 'Setúbal'],
  'Alverca do Ribatejo': ['Vila Franca de Xira', 'Lisboa'],
  'Amora': ['Seixal', 'Setúbal'],
  'Arcozelo': ['Vila Nova de Gaia', 'Porto'],
  'Avintes': ['Vila Nova de Gaia', 'Porto'],
  'Baguim do Monte': ['Gondomar', 'Porto'],
  'Barcarena': ['Oeiras', 'Lisboa'],
  'Barranco do Velho': ['Loulé', 'Faro'],
  'Belas': ['Sintra', 'Lisboa'],
  'Beloura': ['Sintra', 'Lisboa'],
  'Belverde': ['Seixal', 'Setúbal'],
  'Benedita': ['Alcobaça', 'Leiria'],
  'Boliqueime': ['Loulé', 'Faro'],
  'Brandoa': ['Amadora', 'Lisboa'],
  'Bucelas': ['Loures', 'Lisboa'],
  'Cacém': ['Sintra', 'Lisboa'],
  'Cacia': ['Aveiro', 'Aveiro'],
  'Caldas das Taipas': ['Guimarães', 'Braga'],
  'Caliços': ['Albufeira', 'Faro'],
  'Camarate': ['Loures', 'Lisboa'],
  'Canas de Senhorim': ['Nelas', 'Viseu'],
  'Caniçal': ['Machico', 'Ilha da Madeira'],
  'Caparica': ['Almada', 'Setúbal'],
  'Capelas': ['Ponta Delgada', 'Ilha de São Miguel'],
  'Carcavelos': ['Cascais', 'Lisboa'],
  'Carnaxide': ['Oeiras', 'Lisboa'],
  'Carregado': ['Alenquer', 'Lisboa'],
  'Casal de Cambra': ['Sintra', 'Lisboa'],
  'Charneca de Caparica': ['Almada', 'Setúbal'],
  'Colares': ['Sintra', 'Lisboa'],
  'Ericeira': ['Mafra', 'Lisboa'],
  'Ermesinde': ['Valongo', 'Porto'],
  'Esgueira': ['Aveiro', 'Aveiro'],
  'Esmoriz': ['Ovar', 'Aveiro'],
  'Estoril': ['Cascais', 'Lisboa'],
  'Fátima': ['Ourém', 'Santarém'],
  'Fernão Ferro': ['Seixal', 'Setúbal'],
  'Feteiras': ['Ponta Delgada', 'Ilha de São Miguel'],
  'Fogueteiro': ['Seixal', 'Setúbal'],
  'Forte da Casa': ['Vila Franca de Xira', 'Lisboa'],
  'Furnas': ['Povoação', 'Ilha de São Miguel'],
  'Gafanha da Nazaré': ['Ílhavo', 'Aveiro'],
  'Gandra': ['Paredes', 'Porto'],
  'Grandola': ['Grândola', 'Setúbal'],
  'Horta (Angústias)': ['Horta', 'Ilhas Açores (Outras)'],
  'Lavra': ['Matosinhos', 'Porto'],
  'Leça da Palmeira': ['Matosinhos', 'Porto'],
  'Leça do Balio': ['Matosinhos', 'Porto'],
  'Linda-a-Velha': ['Oeiras', 'Lisboa'],
  'Lixa': ['Felgueiras', 'Porto'],
  'Lourel': ['Sintra', 'Lisboa'],
  'Malveira': ['Mafra', 'Lisboa'],
  'Marinha das Ondas': ['Figueira da Foz', 'Coimbra'],
  'Marinhais': ['Salvaterra de Magos', 'Santarém'],
  'Marrazes': ['Leiria', 'Leiria'],
  'Massamá': ['Sintra', 'Lisboa'],
  'Mem Martins': ['Sintra', 'Lisboa'],
  'Mira Sintra': ['Sintra', 'Lisboa'],
  'Miraflores': ['Oeiras', 'Lisboa'],
  'Montelavar': ['Sintra', 'Lisboa'],
  'Mozelos': ['Santa Maria da Feira', 'Aveiro'],
  'Oiã': ['Oliveira do Bairro', 'Aveiro'],
  'Paço de Arcos': ['Oeiras', 'Lisboa'],
  'Parchal': ['Lagoa', 'Faro'],
  'Parede': ['Cascais', 'Lisboa'],
  'Pedroso': ['Vila Nova de Gaia', 'Porto'],
  'Pêra': ['Silves', 'Faro'],
  'Perafita': ['Matosinhos', 'Porto'],
  'Pinhal Novo': ['Palmela', 'Setúbal'],
  'Pinheiro da Bemposta': ['Oliveira de Azeméis', 'Aveiro'],
  'Porto Salvo': ['Oeiras', 'Lisboa'],
  'Póvoa de Santa Iria': ['Vila Franca de Xira', 'Lisboa'],
  'Quarteira': ['Loulé', 'Faro'],
  'Queijas': ['Oeiras', 'Lisboa'],
  'Queluz': ['Sintra', 'Lisboa'],
  'Quinta do Conde': ['Sesimbra', 'Setúbal'],
  'Quinta do Lago': ['Loulé', 'Faro'],
  'Ramada': ['Odivelas', 'Lisboa'],
  'Rio de Mouro': ['Sintra', 'Lisboa'],
  'Rio Tinto': ['Gondomar', 'Porto'],
  'Samora Correia': ['Benavente', 'Santarém'],
  'São Bartolomeu de Messines': ['Silves', 'Faro'],
  'São Cosme': ['Gondomar', 'Porto'],
  'São Domingos de Rana': ['Cascais', 'Lisboa'],
  'São Félix da Marinha': ['Vila Nova de Gaia', 'Porto'],
  'São João da Talha': ['Loures', 'Lisboa'],
  'São Mamede de Infesta': ['Matosinhos', 'Porto'],
  'São Marcos': ['Sintra', 'Lisboa'],
  'São Pedro da Cova': ['Gondomar', 'Porto'],
  'São Pedro do Estoril': ['Cascais', 'Lisboa'],
  'Silveira': ['Torres Vedras', 'Lisboa'],
  'Sobreda': ['Almada', 'Setúbal'],
  'Tapada das Mercês': ['Sintra', 'Lisboa'],
  'Tires': ['Cascais', 'Lisboa'],
  'Tunes': ['Silves', 'Faro'],
  'Valadares': ['Vila Nova de Gaia', 'Porto'],
  'Vale de Lobo': ['Loulé', 'Faro'],
  'Venda do Pinheiro': ['Mafra', 'Lisboa'],
  'Vialonga': ['Vila Franca de Xira', 'Lisboa'],
  'Vila Cova de Lixa': ['Felgueiras', 'Porto'],
  'Vila Frescainha (São Pedro)': ['Barcelos', 'Braga'],
  'Vila Nova de Milfontes': ['Odemira', 'Beja'],
  'Vila Nova de Santo André': ['Santiago do Cacém', 'Setúbal'],
  'Vilamoura': ['Loulé', 'Faro'],
  'Vilar Formoso': ['Almeida', 'Guarda'],
  'Zambujeira do Mar': ['Odemira', 'Beja'],
};

const DISTRICT_BOUNDS = [
  ['Viana do Castelo', 41.6, 42.2, -8.9, -8.1],
  ['Braga', 41.3, 41.9, -8.7, -7.9],
  ['Porto', 40.9, 41.6, -8.8, -7.9],
  ['Vila Real', 41.1, 41.9, -8.1, -7.1],
  ['Bragança', 40.8, 42.2, -7.5, -6.1],
  ['Viseu', 40.2, 41.4, -8.3, -7.1],
  ['Guarda', 40.0, 41.2, -7.8, -6.7],
  ['Aveiro', 40.3, 41.1, -8.9, -8.0],
  ['Coimbra', 39.7, 40.6, -9.1, -7.5],
  ['Castelo Branco', 39.4, 40.5, -8.5, -6.7],
  ['Leiria', 39.3, 40.3, -9.6, -8.0],
  ['Santarém', 38.6, 40.0, -9.1, -7.2],
  ['Portalegre', 38.6, 39.9, -8.2, -6.8],
  ['Lisboa', 38.4, 39.5, -9.5, -8.7],
  ['Setúbal', 37.8, 39.0, -9.3, -8.1],
  ['Évora', 37.8, 39.3, -8.6, -7.0],
  ['Beja', 37.1, 38.6, -9.0, -6.9],
  ['Faro', 36.9, 37.6, -9.1, -7.3],
  ['Ilha da Madeira', 32.6, 33.2, -17.4, -16.2],
  ['Ilha de São Miguel', 37.6, 38.0, -25.9, -25.0],
  ['Ilhas Açores (Outras)', 36.7, 40.0, -31.5, -24.5],
];

function getLocationFromRef(refCode) {
  if (refCode && REF_TO_LOCATION[refCode.toUpperCase()]) {
    return [...REF_TO_LOCATION[refCode.toUpperCase()]];
  }
  return null;
}

function getLocationFromCoords(lat, lng) {
  for (const [district, minLat, maxLat, minLng, maxLng] of DISTRICT_BOUNDS) {
    if (lat >= minLat && lat <= maxLat && lng >= minLng && lng <= maxLng) {
      return [district, district];
    }
  }
  return ['Outros', 'Outros'];
}

function getLocationFromCity(cityName) {
  if (!cityName) return null;
  const cn = cityName.trim();
  if (DISTRICT_MAP[cn]) return [cn, DISTRICT_MAP[cn]];
  const cnLower = cn.toLowerCase();
  for (const [muni, dist] of Object.entries(DISTRICT_MAP)) {
    if (muni.toLowerCase().includes(cnLower) || cnLower.includes(muni.toLowerCase())) {
      return [muni, dist];
    }
  }
  return null;
}

function getLocationFromParish(parishName) {
  if (!parishName) return null;
  const pn = parishName.trim();
  if (PARISH_TO_CONCELHO[pn]) return [...PARISH_TO_CONCELHO[pn]];
  const pnLower = pn.toLowerCase();
  for (const [parish, [muni, dist]] of Object.entries(PARISH_TO_CONCELHO)) {
    if (parish.toLowerCase().includes(pnLower) || pnLower.includes(parish.toLowerCase())) {
      return [muni, dist];
    }
  }
  return null;
}

function getLocationInfo(tags) {
  const ref = tags['ref'] || '';
  if (ref) {
    const refParts = ref.split(';');
    for (const rp of refParts) {
      const parts = rp.trim().split('-');
      if (parts.length >= 2) {
        if (/^[a-zA-Z]+$/.test(parts[0])) {
          const loc = getLocationFromRef(parts[0]);
          if (loc) return loc;
        }
        if (parts.length >= 3 && ['MOBI', 'ADPORTUGAL'].includes(parts[0].toUpperCase()) && /^[a-zA-Z]+$/.test(parts[1])) {
          const loc = getLocationFromRef(parts[1]);
          if (loc) return loc;
        }
      }
    }
  }

  const city = (tags['addr:city'] || '').trim();
  if (city) {
    const loc = getLocationFromCity(city);
    if (loc) return loc;
    const ploc = getLocationFromParish(city);
    if (ploc) return ploc;
  }

  const postcode = tags['addr:postcode'] || '';
  if (postcode && /^\d/.test(postcode)) {
    const firstDigit = postcode[0];
    const pcMap = {
      '1': ['Lisboa', 'Lisboa'], '2': ['Santarém', 'Santarém'],
      '3': ['Coimbra', 'Coimbra'], '4': ['Porto', 'Porto'],
      '5': ['Vila Real', 'Vila Real'], '6': ['Castelo Branco', 'Castelo Branco'],
      '7': ['Évora', 'Évora'], '8': ['Faro', 'Faro'], '9': null
    };
    if (firstDigit === '9') {
      if (postcode.startsWith('95') || postcode.startsWith('96')) {
        return ['Ponta Delgada', 'Ilha de São Miguel'];
      } else if (/\d/.test(postcode[1]) && parseInt(postcode[1]) <= 4) {
        return ['Funchal', 'Ilha da Madeira'];
      } else {
        return ['Angra do Heroísmo', 'Ilhas Açores (Outras)'];
      }
    }
    if (pcMap[firstDigit]) return [...pcMap[firstDigit]];
  }

  return null;
}

module.exports = {
  REF_TO_LOCATION,
  DISTRICT_MAP,
  PARISH_TO_CONCELHO,
  DISTRICT_BOUNDS,
  getLocationFromRef,
  getLocationFromCoords,
  getLocationFromCity,
  getLocationFromParish,
  getLocationInfo
};
